markdown: GFM

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [WACO: Word-Aligned Contrastive Learning for Speech Translation]
description: [Siqi Ouyang<sup>1</sup>, Rong Ye<sup>2</sup>, Lei Li<sup>1</sup><br>
<sup>1</sup>UC Santa Barbara, <sup>2</sup>Bytedance]
